### ISSUE TITLE
Kopieren von Applikationen unvollständig

### ISSUE THREAD

**Issue by Sonnengruesser** [OpenKNX/Kaenx-Creator#10]
ich schreibe jetzt deutsch...
Beim Kopieren einer Applikation (Rechtsklick -> Kopieren) gehen einige Daten verloren:

- in den Parametern der ausgewählte Speicher
- in den ComObjects der TextParameter
- in den ComObjects der Datapoint type und subtype
- in "Dynamisch" alle Inhalte, nur die Objekte bleiben bestehen

**Comment by thewhobox** [comment]
Vielen Dank für das Feedback.
Werde es mir anschauen und fixen

**Comment by Sonnengruesser** [comment]
Noch ein Zusatz, hängt vermutlich auch irgendwie damit zusammen:
Die Auswahl "ParameterRefs automatisch erstellen" und "ComObjectRefs automatisch erstellen" funktionieren nicht. Die Refs werden einfach nicht erstellt/aktualisiert.

**Comment by thewhobox** [comment]
Das kopieren sollte nun komplett funktionieren.
Mit "ParameterRefs automatisch erstellen" und "ComObjectRefs automatisch erstellen" hatte ich allerdings keine Probleme vorher bei einer kopierten Version.

Kannst du das mit der aktuellen Github Version erneut testen bzw genauer beschreiben?

**Comment by Sonnengruesser** [comment]
sorry dass ich keine Rückmeldung gab. Ich konnte/wollte nicht die Build-Umgebung aufsetzen um das Testen zu können. Nicht noch eine Baustelle...
