### ISSUE TITLE
Parameter Type maxvalue comparison problem with float indication. 

### ISSUE THREAD

**Issue by Sonnengruesser** [OpenKNX/Kaenx-Creator#11]
sorry dass ich für alles ein Issue aufmache, aber mir fehlt der Background um mich da reinzuarbeiten.
Ich hab einen Parameter Typ NumberUInt ausgewählt. Manuelle Größe 32Bits. 
Der Maximalwert bleibt erst mal auf den 65k - Vorschlag das automatisch berechnen zu lassen...?

Aber das eigentliche Problem ist, wenn ich manuell den maximalen Wertebereich eingebe (4 294 967 295) wird die Darstellung auf Fließkomma geändert und später beim Veröffentlichen kommt folgender Fehler
![grafik](https://user-images.githubusercontent.com/36325150/193401470-0d85bfa9-964f-41e4-b16f-3868629afe88.png)

Ist es möglich die Änderung der Darstellung im Eingabefeld zu unterdrücken?

**Comment by thewhobox** [comment]
Das ist etwas blöd gelöst muss ich sagen, da ich jeden Wert in einen float umwandle um mir einfach Arbeit zu sparen.
Das hat halt den Nachteil, dass es bei so großen Maximalwerten zu Problemen führt.

Habe auch schon überlegt es erst als string zu speichern und nur beim überprüfen umzuwandeln.
Das würde das Problem evtl lösen. Kam aber noch nicht dazu.

**Comment by thewhobox** [comment]
Hab das mal umgebaut.
Sollte nun problemlos funktionieren.
Habe es mit einer Applikation getestet, die ebenfalls 4294967295 als Maximum verwendet.

Kannst du kurz eine Rückmeldung geben, dass es bei dir auch funktioniert?
