### ISSUE TITLE
multiple module refs

### ISSUE THREAD

**Issue by john30** [OpenKNX/Kaenx-Creator#13]
**Describe the bug**
when adding a module definition more than once, it gets assigned the same ID and will prevent ETS from adding the device with error

**To Reproduce**
1. define a module
2. add the module to the app dynamic more than once on top level
3. export the knxprod
4. import on ETS 
5. add the device to the device list and ETS will report duplicate key error

furthermore, when trying to use the "Zurücksetzen" button in the app dynamic module ref yields in the following exception:
```
Exception has occurred: CLR/System.Exception
An exception of type 'System.Exception' occurred in Kaenx.Creator.dll but was not handled in user code: 'Unbekannter Typ zum ID löschen: System.Windows.Controls.Button'
   at Kaenx.Creator.Controls.DynamicView.ResetId(Object sender, RoutedEventArgs e) in C:\Users\john\Desktop\Kaenx.Creator.git\Kaenx.Creator\Controls\DynamicView.xaml.cs:line 106
```

**Expected behavior**
IDs are kept unique within the same class (here: module ref)

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser irrelevant
 - Version current source

**Comment by thewhobox** [comment]
@john30 thanks for your report.
I can't reproduce the bug with duplicate key.
But i fixed the bug with the reset ID.

I created a module and added it to the RootNode:
![image](https://user-images.githubusercontent.com/45664417/195531942-b7cc9c43-7655-44db-8060-589fdc9c61ff.png)
My Module Dynamic looks like this:
![image](https://user-images.githubusercontent.com/45664417/195532045-1e342373-a31c-4b05-9e7d-fcf96214b1e9.png)

Maybe you can share a ae-manu file and the created knxprod where the bug happens with me?

**Comment by john30** [comment]
seems to be gone with the latest sources, thanks anyway!
