### ISSUE TITLE
"An unhandled exception occurred: Sequence contains no matching element" when importing KnxProd XML

### ISSUE THREAD

**Issue by ginkel** [OpenKNX/Kaenx-Creator#21]
**Describe the bug**
Importing a KnxProd XML fails with the exception: "Sequence contains no matching element"

**To Reproduce**
1. Create a new empty project
2. Attempt to import the XML from https://github.com/thelsing/knx/blob/master/examples/knx-h8i8o/knx-h8i8o.xml (via Importieren -> KnxProd XML)
3. "An unhandled exception occurred: Sequence contains no matching element" causing the import to fail

**Expected behavior**
If the XML is valid (I can't verify if this is the case), I'd expect to be able to import it without errors.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: [e.g. 22] 1.4.2 (downloaded as GitHub release)

**Comment by thewhobox** [comment]
Thank you ginkel for your feedback.

https://github.com/thelsing/knx/blob/master/examples/knx-h8i8o/knx-h8i8o.xml#L11
https://github.com/thelsing/knx/blob/master/examples/knx-h8i8o/knx-h8i8o.xml#L2190
The ApplicationId is invalid.
In the XML it is `M-00FA_A-0000-00-0000` but it has to be `M-00FA_A-07E7-01-0000`.

It may work if you just sign it with the ETS Tools, but for Creator has to be valid in this two lines (Appnumber- and version can be zeroed in all othe Ids).

**Comment by ginkel** [comment]
Thanks for the clarification! Just a suggestion for a possible enhancement: It would be nice to know (from the error message) accessing which element failed.
