### ISSUE TITLE
Does the software support the following image functions

### ISSUE THREAD

**Issue by ct991218620** [OpenKNX/Kaenx-Creator#23]
![b26f9b81aaa60c83d075d500518aed2](https://user-images.githubusercontent.com/15519139/219019590-bc59026c-3ebe-477a-a64c-23aebd47cbd5.png)

**Comment by thewhobox** [comment]
Hello,

no not competly.
You may can add the settings on the right by setting "IsIpEnabled" in Hardware.
The Tunnel Interfaces on the left are not supported yet.

**Comment by ct991218620** [comment]
This software is very good and has helped me a lot. Thank you very much!

**Comment by ct991218620** [comment]
> Hello,
> 
> no not competly. You may can add the settings on the right by setting "IsIpEnabled" in Hardware. The Tunnel Interfaces on the left are not supported yet.

This software is very good and has helped me a lot. Thank you very much!
