### ISSUE TITLE
Edit Procedure CodeEditor Click Save and it will appear "\u003" 

### ISSUE THREAD

**Issue by ct991218620** [OpenKNX/Kaenx-Creator#25]
When I modify some content, '<' will become "\u003"

![1676967313415](https://user-images.githubusercontent.com/15519139/220286688-93256581-5d38-4608-b527-f7ceaef1228a.jpg)

**Comment by thewhobox** [comment]
thank you for your report.
I will create a commit to fix it.

**Comment by ct991218620** [comment]
Ok, look forward to your new version, thank you！

> thank you for your report. I will create a commit to fix it.
