### ISSUE TITLE
Cannot add Items to Repeat Block

### ISSUE THREAD

**Issue by Ravenspark** [OpenKNX/Kaenx-Creator#32]
**Describe the bug**
In current version 1.7.3 I am not able to add any items to a repeat block. All options are disabled.

**To Reproduce**
1. Create a new minimal project (Projekt -> Neu -> Minimal)
2. In Dynamic add a new channel (Applikation -> Dynamisch -> right click on Root -> Channel hinzufügen)
3. Add a repeat block to this channel
4. No ittems can be added to the repeat block

**Expected behavior**
The repeat block should allow to add new items on his level.

**Screenshots**
![Keanx_RepeatBug](https://github.com/OpenKNX/Kaenx-Creator/assets/39969118/e759a2e9-53a1-416b-9336-82b660dd92ba)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: v1.7.3

**Comment by thewhobox** [comment]
Hello,

in this screenshot i can see you have not activates Modules in the General Tab:
![image](https://github.com/OpenKNX/Kaenx-Creator/assets/45664417/936ce2b7-9d74-4ad0-811c-49e6d5d6e8bf)

I will implement in the next version, that adding repeate or modules wont we visible unless the modules are activated.

**Comment by Ravenspark** [comment]
Hi,

thank you very much for the clarification.
We should add this to the wiki. I did not understand that I need to create a module to use the repeat function. :-)

**Comment by thewhobox** [comment]
Hey,

It is ready in the Wiki ;) 
![Screenshot_2024-03-05-22-16-26-422_com microsoft emmx-edit](https://github.com/OpenKNX/Kaenx-Creator/assets/45664417/5ffb1fc1-c82b-428c-b5b2-10f492449c21)
