### ISSUE TITLE
Signature for ETS6

### ISSUE THREAD

**Issue by ptorrent** [OpenKNX/Kaenx-Creator#33]
Hello !

It's not a bug but more a question..

I've changed some information on different XML. And I've automated some procedures to save time... 

The problem is that I cannot reimport my knxproj into ETS because of signature not valid:

In the past I was using this tool :
https://github.com/KARDUINO/SignKnxProd/blob/master/knxsign.cs

But seems not working on ETS 6.

Is your tool able to signe my knxproj file ?

Thanks a lot for your answer !

**Comment by thewhobox** [comment]
This Tool ist not for signing Projects.
