### ISSUE TITLE
TextParameter lost

### ISSUE THREAD

**Issue by Ravenspark** [OpenKNX/Kaenx-Creator#34]
**Describe the bug**
Text parameter selection lost when changeing in other module.

**To Reproduce**
1. Create a new project with at least 2 modules
2. Set text parameter for top block in module1
3. Select module2 and set text parameter there for top block
4. When trying to create an output, module1 has no TextParameter selected anymore

**Expected behavior**

**Screenshots**
![kaenxBug](https://github.com/OpenKNX/Kaenx-Creator/assets/39969118/35bec1e2-4721-4459-b6a5-faa28875d4f9)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: v1.7.3

**Comment by thewhobox** [comment]
Thank you for reposting this bug. 
I fixed it in this commit https://github.com/OpenKNX/Kaenx-Creator-Share/commit/393c5fcf29b4fc26d554f1666ead3439de4ddae3

I will release a new version.
