### ISSUE TITLE
arguments in submodule does not replace the text in ETS 5

### ISSUE THREAD

**Issue by leoujz** [OpenKNX/Kaenx-Creator#37]
for example, i add a module "Button" which has an argument "argChan", there a parameter named "Para {{argChan}}"，with this configuration, "Para {{argChan}}" will be replaced by "Para 1" in a module with argument argChan == 1, when shown in ETS.
However, this does not work in submodule. For example, "Button" module has a submodule with name "Object", which has an argument "argObj", also has a parameter named "Object {{argObj}}", finally in ETS, "Object {{argObj}}" just keeps as it is, {{argObj}} is not replaced with the actual argObj value.

**Comment by leoujz** [comment]
is this related to ETS version? my ETS version is 5.7.4

**Comment by thewhobox** [comment]
Could you provide me an examples ae-manu file where the Bug appears?

**Comment by leoujz** [comment]
[attachments.zip](https://github.com/OpenKNX/Kaenx-Creator/files/15281715/attachments.zip)
here is the ae-manu file and the output.knxprod file, after importing to ETS, set the number of button > 0, set the number of object > 0, then you will see the Object {{argChan}} text which is not converted.
I just don't know what happened in ETS which is a black box, and in the xml extracted from the knxprod, i saw everything ok. maybe there's something out of my knowledge. Thanks for debugging this.

**Comment by thewhobox** [comment]
There were a view bugs with the IDs of the arguments that did not reference anywhere (it only occured in submodules).
After several tests it works now in my ETS (6.2.2).

So this will be fixed in the next release.

Thank you for reporting the bug!
