### ISSUE TITLE
module index in dyamic is repeated

### ISSUE THREAD

**Issue by leoujz** [OpenKNX/Kaenx-Creator#38]
when adding a module into the dynamic, the module ID is -1, which is generated orderly when exporting to knxprod.
however, in a case, i added 8 modules, then pubish, their ID are 1\~8. then i added another 8 modules, publish again, the later 8 modules still have ID 1~8, then the repeated ID causes some problem.
currently, i reset all the IDs of modules, to regenreated them once.

**Comment by thewhobox** [comment]
I can confirm this bug and will fix it in the next release.
