### ISSUE TITLE
latest code in master branch  has bug when used in ETS 5.7.4

### ISSUE THREAD

**Issue by leoujz** [OpenKNX/Kaenx-Creator#39]
export a knxprod with the latest code in master branch, knxprod can be imported to ETS successfully, but when generate a device into a ETS project, it reports an exception error. 
with the same ae-menu project, i use the release version 1.8.0, everything is ok

**Comment by thewhobox** [comment]
Please provide more detailed info!

- Screenshot of exception
- ets log if it helps
- ae-manu file wih reproduceable error

Otherwise i cant help you.
there are so many exceptions the ets know...

**Comment by leoujz** [comment]
i'll provide it later

**Comment by thewhobox** [comment]
Does this bug still appears?
Or can i close the issue?
