### ISSUE TITLE
[Feature Request] Add Parameter Cloning

### ISSUE THREAD

**Issue by uschmelmer** [OpenKNX/Kaenx-Creator#4]
Hi,
i would be great to have the option to clone/copy existing parameters!
You could add a "Clone/Klonen" button next to "Add/Hinzufügen" and "Delete/Löschen" at the top of the parameter list.

Thanks for the great peace of software!

Best Regards,
Udo Schmelmer

**Comment by uschmelmer** [comment]
Hi,
i had a look at the code implemented the feature by myself.
I will test it in the evening and create a merge request.
Udo

**Comment by uschmelmer** [comment]
#5
Done, i will continue with CommObj cloning the same way.

**Comment by thewhobox** [comment]
@uschmelmer thanks for the PR.
Plaese dont open another for the ComObjects Just add it to the existing PR :)

I will test ist tomorrow.

**Comment by uschmelmer** [comment]
@thewhobox alright, i added the ComObjects to the original PR :-)
