### ISSUE TITLE
RGBW is not a valid colorspace value in ETS 5.7.4

### ISSUE THREAD

**Issue by leoujz** [OpenKNX/Kaenx-Creator#40]
using RGBW in ae-menu project, it reports RGB is not a valid colorspace when importing to ETS product catalog. RGB is ok

**Comment by thewhobox** [comment]
There is a difference between "is valid" and "the ets acepts it anyways".
My checks are based on the xsd of the xml files.
So it is invalid without # even if the ets doesnt care about it.
