### ISSUE TITLE
Color parameter type support for color picker.

### ISSUE THREAD

**Issue by anand-010** [OpenKNX/Kaenx-Creator#43]
**Is your feature request related to a problem? Please describe.**
"ParameterType Color Parameter (RGB_BG_COLOR): not supported colorspectrum 5"

**Describe the solution you'd like**
A color picker for selecting rgb value of leds using the color picker in ets.

**Comment by thewhobox** [comment]
Please be more specific.
A color picker is already supported for ets.
![image](https://github.com/user-attachments/assets/0e13a675-ea49-4fc2-83b3-ddca91f7b6e2)

Create a ParameterType Color and select one of RGB/HSV (RGBW not supported by ets, but its a valid option due to knx spec).

**Comment by anand-010** [comment]
![image](https://github.com/user-attachments/assets/182ed15f-60c5-4145-aef9-ea8bd2e78ccd)
I can add the color paramer but when i am add it into the dynamic section the output compilation throws this error.

**Comment by anand-010** [comment]
[4 CHANNEL TOUCH SENSOR.zip](https://github.com/user-attachments/files/16611291/4.CHANNEL.TOUCH.SENSOR.zip)

**Comment by thewhobox** [comment]
Ah i see there is a bug with the wrong error message.
Your error is that your value for the parameter RGB_BG_COLOR is not in the right format.
Valid is "#RRGGBB"
Your value is "1"

**Comment by anand-010** [comment]
It's worked.
Thank you.

**Comment by thewhobox** [comment]
Perfect.
This is fixed with 1.8.4
