### ISSUE TITLE
No root node in dynamic when creating empty project

### ISSUE THREAD

**Issue by thelsing** [OpenKNX/Kaenx-Creator#45]
**Describe the bug**
Dynamic is empty and there is no way to add something to it.

**To Reproduce**
1. create new empty project.
2. go to Application->Dynamic
3. See empty treeview

**Expected behavior**
Rootnote in treeview.

**Screenshots**

<img width="390" alt="image" src="https://github.com/user-attachments/assets/a27f0ed8-379f-4b66-8517-601ce7a79837">

Version is 1.8.4.

**Comment by thewhobox** [comment]
Hm i cant reproduce this issue.
Both current github state and release 1.8.4 works fine on my computer.

I create an empty new project, select 07B0 as MaskVersion.
The Dynamic Root gets created correctly.

You could try to workaround by editing the file by yourself:
`
Dynamics": [
      {
        "$type": "Kaenx.Creator.Models.Dynamic.DynamicMain, Kaenx.Creator.Share",
        "IsExpanded": true,
        "Name": "Root Knoten",
        "Items": []
      }
],
`

Or create a minimal project. Delete everything you dont need and save this as a template.

**Comment by thelsing** [comment]
Save/restore fixed it for me too. For the reproduction I forgot to choose a Mask. Maybe a message "choose Mask-Type first" would help. Feel free to close this issue.

Some other small points I noticed:
- For ComObject you might add a check for Number > 0. It took me a day to figure out why I got no GroupObjects on my device :)
- When you uncheck "OpenKnx Project" it would be nice if the Manufacturer Id would be set do KNXA. 
- Is it intentional that you can't change the Maskversion once choosen? This makes it hard to use the minmal example for other mediums.

You made really much progress in the time I didn't look at this project. There is no need to crack KNX-MT any more ;)

**Comment by thewhobox** [comment]
It should not ne possible to select the Application Tab if you have no Mask selected:
![image](https://github.com/user-attachments/assets/7a7dc153-4d4b-43e3-a70f-ecf43c11e927)

The Mask Version sets also the LoadProcedure (Merge, Product or Mask) and other settings (memory segment relative or absolute, at least i thought it would set it at the beginning) i disabled it to change it.
Maybe i will include this in another release :)
For now you can change it by editing the file itself. The Mask is only a string in the ae-manu.

ComObject check and uncheck openknx are on my list now ;)

:D i still use the MT some times for checking the exported knxprod.

**Comment by thelsing** [comment]
Something else I just remembered: It would be nice if the Loadprocedure for ApplicationObject would be generated automatically. I guess most user don't know what they should add there. Of course they can just look at the minimal example to figure it out.

**Comment by thelsing** [comment]
You can reproduce my original problem if you create the minimal example. Got to App->Dynamic and the create a new empty project.

**Comment by Sonnengruesser** [comment]
Also had the same bug - root was not shown. 
Closing and reopening Kaenx-Creator fixed it.
So this bug is still alive in v1.9.8
