### ISSUE TITLE
No focus on object after click on link to dynamic object

### ISSUE THREAD

**Issue by olterion** [OpenKNX/Kaenx-Creator#51]
After check of a application program with an error in dynamic section there will be a link to the error object in dynamic tree.

![image](https://github.com/user-attachments/assets/fc378a68-9de0-456d-bace-a1e8212e84c7)

After clicking on this link, there sould be the focus on the error object, but only the dynamic section is opened.
The dynamic tree is shown unchanged (as last view of the tree)

The ShowItem method of DynamicView.xaml.cs will be called and in this all dynamic tree entries should be collapsed and only the branch of the specified object should be expanded.

But in GUI there is no change in the dynamic tree visible.

**Comment by olterion** [comment]
In pull request #52 i made changes to show the expanded tree correctly.
But now the object is not selected in dynamic tree.
Maybe there is any solution to select the correct object after clicking the link?

**Comment by thewhobox** [comment]
I already worked on some sort of this...
Its a lot of work, since you also need to find the correct container for the object (TreeViewItem) (recursive for each child!), expand all parents, then check IsSelected on the found TreeViewItem...

I dont now why but i gave it up

**Comment by olterion** [comment]
Very cool solution to select the dynamic element!
Now this issue can be closed for me.
