### ISSUE TITLE
Use of Static Path in MainWindow.xaml.cs

### ISSUE THREAD

**Issue by derGraph** [OpenKNX/Kaenx-Creator#6]
I'm getting an error if I try to import a Knxprod File. I think it has something to do with this code from MainWindow.xaml

Error message:
![image](https://user-images.githubusercontent.com/68235499/187513922-703a97bc-a76c-4372-a573-2820167bdcca.png)

```
private void ClickViewerKnxProd(object sender, RoutedEventArgs e)
        {
            MessageBox.Show("Diese Funktion lädt eine Statische Datei und ist nur für Entwicklungszwecke eingebaut.");
            ViewerWindow viewer = new ViewerWindow(new Viewer.ImporterKnxProd(@"C:\Users\u6\Downloads\output.knxprod"));
            viewer.Show();
        }
```

**Comment by thewhobox** [comment]
You dont import. you want to use the ProdViewer with a KnxProd.

As the Message before says its a static path for developlment.
Its not finished yet and you should not use this function.

To import an KnxProd use the "import" button in the MenuBar.
Then you can open the application in the ProdViewer by right clicking on the version in the application view.
