### ISSUE TITLE
move a german message to resx

### ISSUE THREAD

**Issue by netcorefan** [OpenKNX/Kaenx-Creator#63]
hi!

Could you add german message below in Resources (resx)?

                        var res = System.Windows.MessageBox.Show($"Hersteller der Produktdatenbank stimmt nicht mit dem Hersteller des Projekts über ein.\r\nWollen Sie ihre HerstellerId von {_general.ManufacturerId:X4} auf {manuId:X4} ändern?", "Question", System.Windows.MessageBoxButton.YesNoCancel, System.Windows.MessageBoxImage.Warning);

It appears in 2 places in code

thank you for your big-good job!

regards

**Comment by thewhobox** [comment]
Message was moved and translated.
