### ISSUE TITLE
Static folder reference in ProdViewer

### ISSUE THREAD

**Issue by Sonnengruesser** [OpenKNX/Kaenx-Creator#7]
Sehr cooles tool, die XML-Bastelei ist ja wirklich mühsam, vor allem wenn sich dann mittendrin Objektgrößen ändern....

I tried using the ProdViewer and there seems to be an issue with a static path reference:
https://github.com/OpenKNX/Kaenx-Creator/blob/a5b09fdd5cca39d54d69d9f193f8264e4a982815/Kaenx.Creator/MainWindow.xaml.cs#L480

I get an error saying "path not found".

**Comment by thewhobox** [comment]
Hallo,

vielen Dank. Die Funktion habe ich extra rausgenommen aus dem Menü, da sie immer wieder für Missverständnisse gesorgt hat.
Die Funktion war nur für mich bestimmt (was auch in der Messagebox steht).

Den ProdViewer öffnet man per Rechtsklick auf die Applikationsversion.

**Comment by Sonnengruesser** [comment]
ach so, ich hab das "nur für Entwicklungszwecke" auf die Prod-file Entwicklung bezogen :)

**Comment by thewhobox** [comment]
Ja wie gesagt war etwas zu schwammiug ausgedrückt^^
