### ISSUE TITLE
invalid signature

### ISSUE THREAD

**Issue by Sonnengruesser** [OpenKNX/Kaenx-Creator#8]
When importing an prodfile I get following error message in ETS_5.6:

Masterdaten-Datei hat keine gültige Signatur: Das Id-Attribut wurde nicht deklariert.

No Idea where to look, can you please give a hint?

**Comment by Sonnengruesser** [comment]
Product viewer ist leer, vielleicht liegt's doch an mir. Ich suche weiter.
Export läuft übrigens ohne Warnung oder Fehler durch.

**Comment by thewhobox** [comment]
Kannst du es denn in anderen versionen exportieren?

**Comment by Sonnengruesser** [comment]
Stupid me!
unter "Dynamic" sollte schon was hinterlegt sein...
Ich fände es hilfreich, ein einfaches Beispiel zu haben. Nachdem ich den Stack von thelsing verwende würde mir ein .ae-manu für folgendes sehr helfen:
[https://github.com/thelsing/knx/tree/master/examples/knx-demo](https://github.com/thelsing/knx/tree/master/examples/knx-demo)
Ich beginne langsam durchzublicken auf Basis einer deutlich komplizierteren Applikation, aber die Hürde wäre mit sowas viel geringer.

**Comment by thewhobox** [comment]
Du kannst auch die xml von der Demo importieren.

**Comment by Sonnengruesser** [comment]
aaaah ja.... *facepalm*
Danke dir!

**Comment by thewhobox** [comment]
Für ne gute Doku fehlt mir leider die Zeit :/
Werde demnächst auch die aktuelle Version mal Release. Da gab es doch schon größere Änderungen.

**Comment by Sonnengruesser** [comment]
Ich hänge leider immer noch. Selbst wenn ich eine bestehende prod öffne und diese mit MF ID 250 erstelle, bekomme ich beim Import die Fehlermeldung oben.
Ich weiß die Meldung ist kryptisch, als noch ein wenig Info:
ETS 5
CreateKNX Tool von thelsing funktioniert,

**Comment by thewhobox** [comment]
Ich habe leider keine ETS5.6 und kann es selbst nicht testen.
Mit der ETS 5.7.4 hab ich keine Probleme mit der knx_master.xml

Vergleich mal die zwei knx_master.xml oder kopiere die vom CreateKnxTool nach Data und ersetze meine.

**Comment by Sonnengruesser** [comment]
Danke, von ETS5.6 auf 5.7 hat sich die Struktur der .xml geändert (glaube KNX Secure wurde implementiert). Update der ETS hat das Problem gelöst.
