### ISSUE TITLE
Parameter Suffixes cause problem on change from V1.2 to V1.3

### ISSUE THREAD

**Issue by Sonnengruesser** [OpenKNX/Kaenx-Creator#9]
Just for info:
if a project was created with V1.2 and is then opened with V1.3 there is an error message if there are parameter suffixes defined.
Workaround: just delete all parameter suffixes.

**Comment by thewhobox** [comment]
There should be a message to convert the old file to the new one.
Can you share a v1.2 file with me?

**Comment by Sonnengruesser** [comment]
Ja, message kommt, aber dann auch eine Fehlermeldung, dass beim Konvertieren der Suffixes ein Type mismatch ist (oder so ähnlich).
[TeichsteuerungBackupV12.zip](https://github.com/OpenKNX/Kaenx-Creator/files/9689929/TeichsteuerungBackupV12.zip)
Is jetzt kein großes Thema, Workaround ist ja einfach.

**Comment by Sonnengruesser** [comment]
(hier stand Mist)

**Comment by thewhobox** [comment]
@Sonnengruesser Danke für die Datei.
Hab es gefixt und es funktioniert mit der Datei nun problemlos.
